import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/db";
import { sessions, messages } from "@/db/schema";
import { getSessionUser } from "@/lib/crypto-auth";

let aiInstance: GoogleGenAI | null = null;

function getGeminiClient(): GoogleGenAI {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not defined in your environment variables. Please check Settings secrets.");
    }
    aiInstance = new GoogleGenAI({ apiKey });
  }
  return aiInstance;
}

export async function POST(req: NextRequest) {
  try {
    const { message, history, topic, voiceName, level, sessionId, isSpoken } = await req.json();

    let ai;
    try {
      ai = getGeminiClient();
    } catch (e: any) {
      return NextResponse.json(
        { error: `Gemini não está configurado: ${e.message}. Defina GEMINI_API_KEY nas Configurações.` },
        { status: 400 }
      );
    }

    // Attempt to grab authenticated user session
    const user = await getSessionUser();

    // Initialize Supabase if configured
    let dbSessionId = sessionId;
    let dbEnabled = false;
    let db: any = null;

    try {
      db = getDb();
      dbEnabled = !!db;
    } catch (e) {
      console.warn("Database connection is not configured yet. Proceeding with local session.");
    }

    // Save user's message to Supabase first if db is active and user is authenticated
    if (dbEnabled && db && user) {
      try {
        if (!dbSessionId) {
          const [newSession] = await db.insert(sessions).values({
            userId: user.userId,
            topic: topic || "English Practice",
            level: level || "Iniciante",
            voice: voiceName || "Kore",
            createdHour: new Date().getHours(),
          }).returning({ id: sessions.id });
          dbSessionId = newSession.id;
        }

        if (message) {
          await db.insert(messages).values({
            sessionId: dbSessionId,
            role: "user",
            text: message,
            isSpoken: !!isSpoken,
          });
        }
      } catch (dbErr) {
        console.error("Failed to save user message in Supabase:", dbErr);
      }
    }

    // Build prompting context
    const systemInstruction = `You are Teacher Gem Coach, a premium, supportive personal English tutor specializing in spoken conversation.
Your goal is to teach English with high-quality simulated, real-world dialogue.
The user's English level is: ${level || "Iniciante"}. Adjust your vocabulary, speed, and sentence complexity accordingly.
The current conversation topic is: "${topic || "A general speaking chat"}". Keep the conversation engaging and aligned with this topic.

You MUST respond ALWAYS in valid JSON format matching this schema:
{
  "reply": "your conversational response in English. Max 2-3 sentences. Keep it highly interactive and end with a question.",
  "translation": "a Portuguese translation of your reply",
  "correction": "A friendly feedback in Portuguese correcting any spelling, grammar, or word choices of the user's last input. If they behaved perfectly, say something supportive like 'Ótimo trabalho! Sem erros detectados.'"
}`;

    const formattedHistory = (history || []).map((h: any) => ({
      role: h.role === "tutor" ? "model" : "user",
      parts: [{ text: h.text }],
    }));

    // Add current user prompt
    formattedHistory.push({
      role: "user",
      parts: [{ text: message || "Hello, I am ready to start practicing!" }],
    });

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: formattedHistory.map((msg: any) => msg.parts[0].text).join("\n"),
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("No response content generated by Gemini.");
    }

    let parsedData;
    try {
      parsedData = JSON.parse(responseText.trim());
    } catch (parseErr) {
      console.warn("Retrieved invalid JSON from Gemini, fallback parsing...", responseText);
      parsedData = {
        reply: "Sorry, I had a slight system error parsing the reply. Could you try saying that again?",
        translation: "Desculpe, tive um leve erro ao analisar a resposta. Você poderia falar de novo?",
        correction: "Não foi possível analisar seus erros nesse momento.",
      };
    }

    const englishReply = parsedData.reply || "Wonderful! Let's continue.";

    // Save tutor's response inside Supabase
    if (dbEnabled && db && dbSessionId && user) {
      try {
        await db.insert(messages).values({
          sessionId: dbSessionId,
          role: "tutor",
          text: englishReply,
          translation: parsedData.translation || "",
          correction: parsedData.correction || "",
          audioBase64: null,
          isSpoken: false,
        });
      } catch (dbErr) {
        console.error("Failed to save tutor response in Supabase:", dbErr);
      }
    }

    return NextResponse.json({
      reply: englishReply,
      translation: parsedData.translation || "Sem tradução disponível.",
      correction: parsedData.correction || "Excelente!",
      audioBase64: null, // synthesized client side
      sessionId: dbSessionId,
    });

  } catch (error: any) {
    console.error("api/chat error:", error);
    return NextResponse.json(
      { error: error?.message || "An internal error occurred." },
      { status: 500 }
    );
  }
}
