import { GoogleGenAI, Type } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/db";
import { sessions, messages } from "@/db/schema";

let aiInstance: GoogleGenAI | null = null;

function getGeminiClient() {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is not defined in environment variables. Please check Settings > Secrets.");
    }
    aiInstance = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiInstance;
}

export async function POST(req: NextRequest) {
  try {
    const { message, history, topic, voiceName, level, sessionId, isSpoken } = await req.json();

    const ai = getGeminiClient();

    // Try to initialize external persistence via Supabase
    let dbSessionId = sessionId;
    let dbEnabled = false;
    let db: any = null;

    try {
      db = getDb();
      dbEnabled = !!db;
    } catch (e) {
      console.warn("Database connection is not configured yet. Proceeding with in-memory chat session.");
    }

    // Save user's incoming message beforehand if DB is available
    if (dbEnabled && db) {
      try {
        if (!dbSessionId) {
          const [newSession] = await db.insert(sessions).values({
            topic: topic || "Ordering Food at a Restaurant",
            level: level || "Iniciante",
            voice: voiceName || "Kore",
            createdHour: new Date().getHours(),
          }).returning({ id: sessions.id });
          dbSessionId = newSession.id;
        }

        if (message) {
          await db.insert(messages).values({
            sessionId: dbSessionId,
            role: "user",
            text: message,
            isSpoken: !!isSpoken,
          });
        }
      } catch (dbErr) {
        console.error("Failed to save user dialog message inside Supabase:", dbErr);
      }
    }

    // 1. Build the prompt for conversational English tutoring
    const systemInstruction = `You are Teacher Gem Coach, a premium, supportive personal English tutor specializing in spoken conversation.
Your goal is to teach English with high-quality simulated, real-world dialogue.
The active lesson topic is: "${topic || "Ordering Food at a Restaurant"}".
The student's English proficiency level: "${level || "Beginner"}". Adjust your vocabulary and grammar complexity accordingly (use simple terms for beginners, natural advanced phrases for advanced students).

Your response MUST be a structured JSON object containing:
1. "reply": Your conversational reply in English, continuing the dialogue and asking a natural/engaging follow-up question. (e.g. "That's great! Would you like chocolate sprinkles on your cappuccino?")
2. "correction": Constructive and encouraging feedback on the student's latest input, written in Portuguese. Point out any grammar, vocabulary, or pronunciation-spelling mistakes gently and show the corrected version. If they did perfectly or had zero errors, write a friendly compliment in Portuguese. Keep it to 1 or 2 concise, supportive sentences.
3. "translation": The direct Portuguese translation of your "reply" so the student can study and learn new words.

Return ONLY the JSON matching the responseSchema. Do not include markdown formatting or outer code blocks.`;

    // We can format history for the prompt context
    const structuredHistory = history && history.length > 0
      ? history.map((h: { role: string; content: string }) => `${h.role === 'user' ? 'Student' : 'Tutor'}: "${h.content}"`).join("\n")
      : "No previous conversation.";

    const promptText = `Conversation History:\n${structuredHistory}\n\nStudent's latest input: "${message || "Hello, I am ready to start the lesson!"}"\n\nPlease reply of the active topic "${topic}".`;

    // Get the JSON response
    const textResponse = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptText,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            reply: {
              type: Type.STRING,
              description: "The conversation reply in English suited for teaching.",
            },
            correction: {
              type: Type.STRING,
              description: "Grammar / dialogue feedback in Portuguese.",
            },
            translation: {
              type: Type.STRING,
              description: "The Portuguese translation of the reply.",
            },
          },
          required: ["reply", "correction", "translation"],
        },
      },
    });

    const resultText = textResponse.text;
    if (!resultText) {
      throw new Error("No response generated by the AI model.");
    }

    // Parse the generated text to fetch the reply
    const parsedData = JSON.parse(resultText);
    const englishReply = parsedData.reply || "Hello! Let's continue practicing.";

    // 2. Synthesize speech using the Gemimi Live preview TTS model with premium female voice selection
    // Selected voice can be 'Kore' (warm, supportive) or 'Zephyr' (dynamic, bright), default to 'Kore' as a premium female voice
    const activeVoice = voiceName === "Zephyr" ? "Zephyr" : "Kore";

    let base64Audio = "";
    try {
      const speechPrompt = `Say warmly and clearly in premium native English: ${englishReply}`;
      
      const speechRes = await ai.models.generateContent({
        model: "gemini-3.1-flash-tts-preview",
        contents: [{ parts: [{ text: speechPrompt }] }],
        config: {
          responseModalities: ["AUDIO"],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: activeVoice },
            },
          },
        },
      });

      const audioPart = speechRes.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      if (audioPart) {
        base64Audio = audioPart;
      }
    } catch (speechErr) {
      console.error("Speech synthesis failed, proceeding with text-only reply:", speechErr);
    }

    // Save tutor's response in Supabase if DB is active
    if (dbEnabled && db && dbSessionId) {
      try {
        await db.insert(messages).values({
          sessionId: dbSessionId,
          role: "tutor",
          text: englishReply,
          translation: parsedData.translation || "",
          correction: parsedData.correction || "",
          audioBase64: base64Audio || null,
          isSpoken: false,
        });
      } catch (dbErr) {
        console.error("Failed to save tutor reply into Supabase database:", dbErr);
      }
    }

    return NextResponse.json({
      reply: englishReply,
      correction: parsedData.correction || "Ótimo trabalho!",
      translation: parsedData.translation || "",
      audioBase64: base64Audio,
      sessionId: dbSessionId,
    });

  } catch (error: any) {
    console.error("API /api/chat error:", error);
    return NextResponse.json(
      { error: error?.message || "An error occurred during speech and text tutor generation." },
      { status: 500 }
    );
  }
}
